# Generated by Django 5.0.7 on 2024-07-19 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=80)),
                ('decripcion', models.TextField(max_length=150)),
                ('texto', models.TextField(max_length=1500)),
                ('imagen', models.ImageField(upload_to='imagenes/')),
                ('fecha', models.DateField()),
            ],
        ),
    ]
